meta_product_name: "Cryptopilot"
meta_title: "Cryptopilot - Track your investments"
meta_description: "Track your investments, quickly and easily"
meta_image: "cover.png" # should exist in `app/assets/images/`
